stages:
  - audit
  - lint
  - test

default:
  image: node:24.12
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

audit:
  stage: audit
  script:
    - npm audit --audit-level=moderate

codestyle:
  stage: lint
  script:
    - npm run lint:ci -- --format gitlab
  artifacts:
    reports:
      codequality: gl-codequality.json

type-check:
  stage: lint
  script:
    - npm run type-check

test api:
  stage: test
  script:
    - cp $FILE_ENV .env
    - npm test
  after_script:
    - npm run allure:generate
  artifacts:
    when: always
    paths:
      - reports/html-report
      - reports/allure-report
      - reports/allure-results

