stages:
  - audit
  - lint

audit:
  stage: audit
  image: node:24.12
  script:
    - npm ci
    - npm audit
#  --audit-level=moderate

codestyle:
  stage: lint
  image: node:24.12
  script:
    - npm ci
    - npm run lint:ci -- --format gitlab
  artifacts:
    reports:
      codequality: gl-codequality.json

type-check:
  stage: lint
  image: node:24.12
  script:
    - npm ci
    - npm run type-check
